### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by pashanaumov** [eran-pinhas/react-native-bubble-picker#2]
@eran-pinhas , great library! 
Do you think it'd be possible to add some functionality for supporting images as a background? 
Thanks!

**Comment by eran-pinhas** [comment]
@pavelnaumov Thank you very much :) 

It depends on the native libraries we use. I think the iOS library has the support so it's possible. Regarding the Android - I'm not sure.

Anyway, I'm not working neither I'm in need for this feature so I wouldn't work on it unless I have some free time

If you want to work on it and PR it would be awesome, and I'll be glad to help

**Comment by pashanaumov** [comment]
Thanks for your quick reply @eran-pinhas !
I will start looking into in soon, will let you know how it goes.
Cheers!

**Comment by ghost** [comment]
any update?

**Comment by eran-pinhas** [comment]
@ODINA101 Nope, sorry.

But I would gladly help do the change if you want to contribute and open a PR
